In [2]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
import numpy as np

In [5]:
array1 = np.array(l)
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
#  type of an array
type(array1)

numpy.ndarray

In [7]:
#  shape of an array
array1.shape

(3, 3)

In [10]:
#  Transpose of matrix (We have to assign back to variable)
array1.T
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
array2 = array1.T
array2

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [16]:
#  reshape the matrix
matrix_2 = [[1,2,3],[4,5,6]]
np.array(matrix_2).shape


(2, 3)

In [17]:
np.array(matrix_2).reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
#  arange 
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
#  slicing with step argument
arr[1:-2:2]

array([2, 4, 6, 8])

In [25]:
array1 = np.array(l)
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
array1[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [27]:
array1[1:2,1:2]

array([[5]])

In [28]:
#  dtype
array1.dtype

dtype('int32')

In [29]:
#  if you change one element data type, entire array datatype changes

In [32]:
type(array1[1,1])

numpy.int32

In [33]:
import os
os.getcwd()

'C:\\Users\\Ajay\\Desktop\\GreyAtom Sessions\\C4- Manipulating Data using Numpy'

In [34]:
ls

 Volume in drive C has no label.
 Volume Serial Number is F41C-3AC2

 Directory of C:\Users\Ajay\Desktop\GreyAtom Sessions\C4- Manipulating Data using Numpy

19-05-2019  16:01    <DIR>          .
19-05-2019  16:01    <DIR>          ..
19-05-2019  14:04    <DIR>          .ipynb_checkpoints
19-05-2019  16:01             6,409 C4-Manipulating data using Numpy.ipynb
19-05-2019  15:43           413,479 weather_small_2012.csv
               2 File(s)        419,888 bytes
               3 Dir(s)  86,755,475,456 bytes free


In [38]:
#  importing csv data as numpy array ,delimiter- for csv is ',', skip_header is skipping no. of rows
weather = np.genfromtxt('weather_small_2012.csv',delimiter=',',skip_header=1)
weather

array([[   nan,  -1.8 ,  -3.9 , ...,   4.  ,   8.  , 101.24],
       [   nan,  -1.8 ,  -3.7 , ...,   4.  ,   8.  , 101.24],
       [   nan,  -1.8 ,  -3.4 , ...,   7.  ,   4.  , 101.26],
       ...,
       [   nan,  -0.5 ,  -1.5 , ...,  28.  ,   4.8 ,  99.95],
       [   nan,  -0.2 ,  -1.8 , ...,  28.  ,   9.7 ,  99.91],
       [   nan,   0.  ,  -2.1 , ...,  30.  ,  11.3 ,  99.89]])

In [37]:
weather.shape

(8785, 7)

In [41]:
#  take out temperature column
temperature = weather[:,1:2]
temperature

array([[-1.8],
       [-1.8],
       [-1.8],
       ...,
       [-0.5],
       [-0.2],
       [ 0. ]])

In [42]:
a =[1,2,3,4]
a= [x**2 for x in a]
a

[1, 4, 9, 16]

In [43]:
a= np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [45]:
farenheit = (temperature*9/5)+32
farenheit

array([[28.76],
       [28.76],
       [28.76],
       ...,
       [31.1 ],
       [31.64],
       [32.  ]])

In [57]:
#  dew point temperature

dew_pt_temp = weather[:,2:3]
dew_pt_temp

array([[-3.9],
       [-3.7],
       [-3.4],
       ...,
       [-1.5],
       [-1.8],
       [-2.1]])

In [58]:
#  added_temp is sum of temperature and dew point temperature
added_temp = temperature + dew_pt_temp
added_temp

array([[-5.7],
       [-5.5],
       [-5.2],
       ...,
       [-2. ],
       [-2. ],
       [-2.1]])

In [56]:
#  divide two matrix array 
A = np.arange(1,10).reshape(3,3)
B = np.arange(11,20).reshape(3,3)

In [55]:
A/B

array([[0.09090909, 0.16666667, 0.23076923],
       [0.28571429, 0.33333333, 0.375     ],
       [0.41176471, 0.44444444, 0.47368421]])

    Find temperature that are above 0 degree celcius and save it greater_than_0
    
    Print temperature and greater_than_0
    
    Print type of greater_than_0 isnf type()
    
    Print type of greater_than_0 using dtype

In [60]:
greater_than_0 = temperature[temperature>0]
greater_than_0

array([0.2, 0.8, 1.8, ..., 0.6, 0.1, 0.2])

In [62]:
#  working with two conditions
temperature[(temperature>0) & (temperature<10)]

array([0.2, 0.8, 1.8, ..., 0.6, 0.1, 0.2])

In [63]:
#  minimum and maximum,median,argmax,argmin
temperature.min()

-23.3

In [64]:
temperature.max()

33.0

In [65]:
temperature.mean()

8.798144353369764

In [66]:
temperature.argmax()

4143

In [67]:
np.median(temperature)

9.3

In [4]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(11,20).reshape(3,3)
a*b


array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [34]:
#  Diabetes data work
#  dtype = 'U32' is used to dispaly text into numpy array
diabetes_with_header = np.genfromtxt('diabetes.csv',delimiter=',',dtype = 'U32')
diabetes_without_header = np.genfromtxt('diabetes.csv',delimiter=',',skip_header=1)

In [36]:
#  only taking out header as a list
header = list(diabetes_with_header[0])
header

['pregnancies',
 'glucose',
 'diastolic',
 'triceps',
 'insulin',
 'bmi',
 'dpf',
 'age',
 'diabetes']

In [44]:
# astype is use to convert entire data column into desired datatype,here converting data columns into float
diabetes_with_header[1:,-1:]


array([['1'],
       ['0'],
       ['1'],
       ['0'],
       ['1'],
       ['0'],
       ['1'],
       ['0'],
       ['1'],
       ['1'],
       ['0'],
       ['1'],
       ['0'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['1'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['1'],
       ['0'],
       ['1'],
       ['0'],
       ['0'],
       ['0'],
       ['1'],
      

In [45]:
sum(diabetes_with_header[1:,-1:])

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U32') dtype('<U32') dtype('<U32')

In [46]:
#  with diabetes_with_header data
sum(diabetes_with_header[1:,-1:].astype(float))

array([268.])

In [39]:
#  with diabetes_without_header data as we are skipping header line while loading data
sum(diabetes_without_header[:,-1:])

array([268.])

In [41]:
diabetes_without_header.shape

(768, 9)

In [51]:
# random array generation
# random.randn - Normal distribution
# random.rand - random distribution
print(np.random.rand(5))
print(np.random.randn(5))

[0.45088655 0.35397009 0.44985046 0.72215436 0.5037388 ]
[-0.55543477 -0.93710286 -1.05419855  0.50348648 -0.18923848]


In [52]:
#  random integer 
np.random.randint(1,10)

9

In [65]:
#  random integer of size =5
#  learn more about seed - seed gets random number and will be same universally and will not change, 
# in bracket number is nothing but code uses to generate random numbers
np.random.seed(40)
np.random.randint(1,100,size=50)

array([71, 92,  8, 38, 57, 51, 66, 13, 72, 20, 32, 75, 56, 84, 60, 92, 74,
       97, 50, 54, 74,  9, 53, 31, 80, 15, 93, 59, 75, 23,  4, 92, 72, 56,
       84, 29, 14, 38, 83, 51, 80, 68, 31, 61, 45, 47, 88, 44, 36, 99])